import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import ExcelJS from 'exceljs';
import {PGlite} from '../../tools/pglite/package/dist/index.js';
Object.assign(process.env,{NODE_ENV:'test',PGHOST:'localhost',PGDATABASE:'isolated_test',PGUSER:'test',PGPASSWORD:'test',SESSION_SECRET:'isolated-test-secret-32-characters-long'});
const engine=new PGlite();
await engine.exec(await fs.readFile('database/schema.sql','utf8'));
await engine.exec('CREATE ROLE vincco_app');
for(const f of ['001_work_rounds.sql','004_historical_import.sql','004_historical_import.sql'])await engine.exec(await fs.readFile('database/migrations/'+f,'utf8'));
const {pool}=await import('../../dist/db/pool.js');
pool.connect=async()=>({query:async(s,a)=>{const r=await engine.query(s,a);return {...r,rowCount:r.rows.length};},release(){}});
const {generateMonthlyClosing}=await import('../../dist/modules/reports/reports.service.js');
try {
 const one=async(sql,args)=>(await engine.query(sql,args)).rows[0];
 const c=(await one("SELECT campaign_id AS id FROM campaigns WHERE name='SILIMEX'")).id;
 const u=(await one("INSERT INTO users(username,password_hash,full_name,role) VALUES('hist-test','!','Histórico','agent') RETURNING user_id AS id")).id;
 const cl=(await one("INSERT INTO clients(source_namespace,clave) VALUES('historical-test','ONE') RETURNING client_id AS id")).id;
 const a=(await one('INSERT INTO contact_assignments(client_id,campaign_id,agent_id) VALUES($1,$2,$3) RETURNING assignment_id AS id',[cl,c,u])).id;
 const ch=(await one("SELECT channel_id AS id FROM channels WHERE campaign_id=$1 AND code='SE_ENVIA_PROMOCION_POR_CORREO'",[c])).id;
 for(const [date,end,issue] of [['2026-08-01 10:00:00-07','2026-08-01 10:01:00-07',null],['2026-09-01 10:00:00-07','2026-09-01 10:01:00-07',null],['2026-09-02 10:00:00-07',null,'Sin hora verificable']])await engine.query("INSERT INTO call_attempts(idempotency_key,assignment_id,campaign_id,client_id,agent_id,dialed_number,origin,state,call_start,call_end,duration_issue,channel_id) VALUES($1,$2,$3,$4,$5,'1234567890','import','closed',$6,$7,$8,$9)",[crypto.randomUUID(),a,c,cl,u,date,end,issue,ch]);
 await engine.query("INSERT INTO historical_monthly_totals VALUES($1,2026,8,100,80,0,10,20,0,0,50,40,'source.xlsx','hash')",[c]);
 const v=(await one("INSERT INTO questionnaire_versions(campaign_id,version_name,is_active) VALUES($1,'Anterior',false) RETURNING version_id AS id",[c])).id;
 const q=(await one("INSERT INTO questionnaire_questions(version_id,code,question_text,question_type,required,display_order) VALUES($1,'H1','Pregunta anterior','text',false,1) RETURNING question_id AS id",[v])).id;
 const attempt=(await one('SELECT min(attempt_id) AS id FROM call_attempts')).id;
 await engine.exec('BEGIN');
 const retiredSurvey=(await one("INSERT INTO call_surveys(attempt_id,campaign_id,version_id,state,started_at,completed_at) VALUES($1,$2,$3,'completed','2026-08-01 10:00:00-07','2026-08-01 10:00:00-07') RETURNING survey_id AS id",[attempt,c,v])).id;
 await engine.query('INSERT INTO survey_answers(survey_id,version_id,question_id,answer_text) VALUES($1,$2,$3,$4)',[retiredSurvey,v,q,'Respuesta histórica']);
 await engine.exec('COMMIT');
 const independent=(await one("INSERT INTO clients(source_namespace,clave) VALUES('historical-test','TWO') RETURNING client_id AS id")).id;
 await engine.query("INSERT INTO historical_survey_records(client_id,campaign_id,agent_id,version_id,completed_at,answers,source_file,source_sha256,source_row) VALUES($1,$2,$3,$4,'2026-09-03 10:00:00-07',$5,'source.xlsx','hash',1)",[independent,c,u,v,JSON.stringify([{questionId:q,option:null,text:'Respuesta original'}])]);
 assert.equal((await one('SELECT count(*)::int AS n FROM vw_contactos_finalizados WHERE client_id=$1',[independent])).n,1);
 await assert.rejects(engine.query('INSERT INTO contact_assignments(client_id,campaign_id,agent_id) VALUES($1,$2,$3)',[independent,c,u]),/finalizado/);
 const wb=new ExcelJS.Workbook();await wb.xlsx.load((await generateMonthlyClosing({campaignId:c,year:2026,month:9})).buffer);
 assert.equal(wb.getWorksheet('CONCENTRADO').getCell('C9').value,100,'official August replaces one detailed call');
 assert.equal(wb.getWorksheet('SILIMEX').getCell('D1').value.result,102,'no double counting');
 assert.equal(wb.getWorksheet('SILIMEX').getCell('G1').value.toISOString(),'1899-12-30T00:00:40.000Z');
 assert.equal(wb.getWorksheet('SILIMEX').getCell('G2').value.toISOString(),'1899-12-30T00:01:00.000Z','invalid time excluded from denominator');
 assert.equal(wb.getWorksheet('SILIMEX').getCell('H11').value,null);
 assert.equal(wb.getWorksheet('ENCUESTA').getCell('F2').value,'Respuesta original');
 assert.equal((await one('SELECT count(*)::int AS n FROM call_attempts')).n,3,'independent survey creates no call');
 assert.ok(wb.getWorksheet('NOTAS DEL INFORME').rowCount>=4);
 console.log('PASS historical migration, separate totals, independent surveys, finalized exclusion and verified-duration TPA');
} finally {await pool.end();await engine.close();}
