import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import ExcelJS from 'exceljs';
const root=fileURLToPath(new URL('../../',import.meta.url)).replaceAll('\\','/').replace(/\/$/,'');
const {PGlite}=await import('file:///'+root+'/tools/pglite/package/dist/index.js');
Object.assign(process.env,{NODE_ENV:'test',PGHOST:'localhost',PGPORT:'5432',PGDATABASE:'isolated_test',PGUSER:'test',PGPASSWORD:'test',SESSION_SECRET:'isolated-test-secret-32-characters-long'});
const engine=new PGlite();
await engine.exec(await fs.readFile(root+'/database/schema.sql','utf8'));
await engine.exec('CREATE ROLE vincco_app');
await engine.exec(await fs.readFile(root+'/database/migrations/001_work_rounds.sql','utf8'));
await engine.exec(await fs.readFile(root+'/database/migrations/002_import_blacklist.sql','utf8'));
const {pool}=await import('file:///'+root+'/dist/db/pool.js');
pool.connect=async()=>({query:async(text,args)=>{const r=await engine.query(typeof text==='string'?text:text.text,args??[]);return {...r,rowCount:r.rows.length||r.affectedRows||0};},release(){}});
const {importContactsFromExcel}=await import('file:///'+root+'/dist/modules/contacts/import.service.js');
const query=async(text,args=[])=>(await engine.query(text,args)).rows;
const headers=['CLAVE','MARCA','TIPO DE COMPRA','RAZÓN SOCIAL','TEL','EXT ','REF1','REF2','CELULAR','CONTACTO','CORREO','EJECUTIVO','STATUS','NUEVO NUMERO','NUEVO CORREO','NUEVO CONTACTO'];
const row=(key,status='',newPhone='',newEmail='',newName='')=>[key,'','COMBINADO','Prueba '+key,'5555555555','','','','','Original','original@example.com','Agente',status,newPhone,newEmail,newName];
let run=0;
async function file(rows){const w=new ExcelJS.Workbook();const s=w.addWorksheet('BASE');s.addRow(headers);rows.forEach(r=>s.addRow(r));w.creator='Prueba '+(++run);return Buffer.from(await w.xlsx.writeBuffer());}
try {
 const admin=(await query("INSERT INTO users(username,password_hash,full_name,role) VALUES('import-admin','unused','Prueba','admin') RETURNING user_id"))[0].user_id;
 const agent=(await query("INSERT INTO users(username,password_hash,full_name,role) VALUES('import-agent','unused','Prueba','agent') RETURNING user_id"))[0].user_id;
 const other=(await query("INSERT INTO users(username,password_hash,full_name,role) VALUES('import-other','unused','Otro','agent') RETURNING user_id"))[0].user_id;
 const campaign=(await query("SELECT campaign_id FROM campaigns WHERE name='PARTNER DELL'"))[0].campaign_id;
 const round=(await query("INSERT INTO work_rounds(campaign_id,agent_id,name) VALUES($1,$2,'Prueba') RETURNING round_id",[campaign,agent]))[0].round_id;
 await query("INSERT INTO work_rounds(campaign_id,agent_id,name) VALUES($1,$2,'Otro')",[campaign,other]);
 const execute=async(buffer,agentId=agent)=>importContactsFromExcel({fileBuffer:buffer,fileName:'prueba.xlsx',campaignId:campaign,userId:admin,agentId});
 const directory=row('ACA');directory[1]='SUCURSAL';
 const first=await file([row('TEST1'),row('TEST2','BLACKLIST'),row('TEST3','NUEVOS DATOS','5555559999','nuevo@example.com','Nuevo'),directory]);
 const summary=await execute(first);
 assert.equal(summary.rowsProcessed,3);assert.equal(summary.imported,3);assert.equal(summary.blacklisted,1);assert.equal(summary.skipped,1);assert.equal(summary.rejected,0,JSON.stringify(summary));
 assert.equal((await query('SELECT count(*)::int n FROM clients'))[0].n,3);
 assert.equal((await query('SELECT count(*)::int n FROM contact_assignments WHERE round_id=$1',[round]))[0].n,3);
 assert.equal((await query('SELECT count(*)::int n FROM call_attempts'))[0].n,0);
 assert.equal((await query('SELECT count(*)::int n FROM vw_contactos_disponibles'))[0].n,2);
 const block=(await query('SELECT * FROM contact_blacklist'))[0];assert.equal(block.attempt_id,null);assert.ok(block.import_detail_id);
 const updated=(await query("SELECT cp.* FROM contact_persons cp JOIN clients c USING(client_id) WHERE c.clave='TEST3'"))[0];
 assert.equal(updated.nombre,'Nuevo');
 assert.deepEqual((await query('SELECT number FROM phone_numbers WHERE contact_id=$1 AND is_active',[updated.contact_id])).map(r=>r.number),['5555559999']);
 assert.equal((await query('SELECT count(*)::int n FROM phone_numbers WHERE contact_id=$1 AND NOT is_active',[updated.contact_id]))[0].n,1);
 console.log('PASS directory excluded, round assigned, imported blacklist hides without creating calls, explicit updates replace active values');
 await assert.rejects(execute(first),e=>e.code==='DUPLICATE_IMPORT');
 // App changes made after an import survive the same explicit old Excel values.
 await query("UPDATE contact_persons SET nombre='Corregido en app' WHERE contact_id=$1",[updated.contact_id]);
 const repeat=await execute(await file([row('TEST1'),row('TEST2'),row('TEST3','NUEVOS DATOS','5555559999','nuevo@example.com','Nuevo')]));
 assert.equal(repeat.rejected,0);assert.equal(repeat.blacklisted,1);assert.equal(repeat.duplicate,3);
 assert.equal((await query('SELECT nombre FROM contact_persons WHERE contact_id=$1',[updated.contact_id]))[0].nombre,'Corregido en app');
 assert.equal((await query('SELECT count(*)::int n FROM contact_persons'))[0].n,3);
 console.log('PASS reimport preserves app corrections and existing blacklist, no duplicate contacts');
 const conflict=await execute(await file([row('TEST1','NUEVOS DATOS','','other@example.com','Intruso')]),other);
 assert.equal(conflict.rejected,1);assert.match(conflict.issues[0].message,/otro agente/);
 assert.equal((await query("SELECT count(*)::int n FROM email_addresses WHERE email='other@example.com'"))[0].n,0);
 const invalid=await execute(await file([row('TEST4','UNKNOWN'),row('TEST5','NUEVOS DATOS','abc'),row('TEST6','NUEVOS DATOS','','bad'),row('TEST7'),row('TEST7')]));
 assert.equal(invalid.rejected,4);assert.equal(invalid.imported,1);assert.equal(invalid.issues.length,4);
 assert.equal((await query("SELECT count(*)::int n FROM clients WHERE clave IN ('TEST4','TEST5','TEST6')"))[0].n,0);
 console.log('PASS cross-agent conflict and invalid rows roll back with visible reasons');
 const multiple=await execute(await file([row('TEST8','NUEVOS DATOS','','one@example.com/two@example.com;three@example.com')]));
 assert.equal(multiple.rejected,0);
 assert.equal((await query("SELECT count(*)::int n FROM email_addresses e JOIN contact_persons cp USING(contact_id) JOIN clients c USING(client_id) WHERE c.clave='TEST8' AND e.is_active"))[0].n,3);
 console.log('PASS multiple new email addresses are imported separately');
 await assert.rejects(query("INSERT INTO contact_blacklist(client_id,campaign_id,reason) VALUES($1,$2,'sin origen')",[block.client_id,campaign]));
 await assert.rejects(query('UPDATE contact_blacklist SET reason=$2 WHERE blacklist_id=$1',[block.blacklist_id,'alterado']));
 await query('UPDATE contact_blacklist SET ended_at=clock_timestamp() WHERE blacklist_id=$1',[block.blacklist_id]);
 assert.equal((await query('SELECT count(*)::int n FROM call_attempts'))[0].n,0);
 console.log('PASS blacklist origin protected; administrator can release without inventing historical calls');
 const {openCall}=await import('file:///'+root+'/dist/modules/calls/calls.service.js');
 const target=(await query("SELECT a.* FROM contact_assignments a JOIN clients c USING(client_id) WHERE c.clave='TEST1'"))[0];
 const attempt=await openCall({agentId:agent,campaignId:campaign,clientId:target.client_id,assignmentId:target.assignment_id,contactId:target.contact_id,dialedNumber:'5555555555',idempotencyKey:'00000000-0000-4000-8000-000000000001'},agent);
 const channel=(await query("SELECT channel_id FROM channels WHERE campaign_id=$1 AND code='NUMERO_EQUIVOCADO'",[campaign]))[0].channel_id;
 await query("UPDATE call_attempts SET state='closed',call_end=clock_timestamp(),channel_id=$2 WHERE attempt_id=$1",[attempt.attempt_id,channel]);
 const callBlock=(await query('SELECT * FROM contact_blacklist WHERE attempt_id=$1',[attempt.attempt_id]))[0];
 assert.ok(callBlock);assert.equal(callBlock.import_detail_id,null);
 console.log('PASS normal call-driven blacklist still works after migration');
} finally {await pool.end();await engine.close();}
