const $=id=>document.getElementById(id);
const channels=[['NO_LE_INTERESA_INFORMACION','No le interesa información','BLACKLIST'],['NUMERO_EQUIVOCADO','Número equivocado','BLACKLIST'],['NUEVOS_DATOS_RAZON_SOCIAL','Cambio de razón social','BLACKLIST'],['BLACKLIST','Blacklist','BLACKLIST'],['NO_CONTESTA','No contesta','NO_CONTESTA'],['BUZON','Buzón','SEGUIMIENTO'],['SE_ENVIA_PROMOCION_POR_CORREO','Se envía promoción por correo','EXITOSO']];
let step=0,question=0,answers=['',''],declined=false,channel='',started=0,ended=0,closed=false,withSurvey=true,newBusiness='';
const questions=['¿Qué marca utiliza principalmente en su negocio?','¿Le gustaría recibir información sobre los productos?'];
const options=[['Silimex','Otra marca','No utiliza estos productos'],['Sí','No']];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let preference;try{preference=localStorage.getItem('vincco-preview-theme')}catch{}
function theme(dark){document.body.classList.toggle('dark',dark);$('theme').textContent=dark?'☀ Modo claro':'☾ Modo oscuro';$('theme').setAttribute('aria-pressed',String(dark));try{localStorage.setItem('vincco-preview-theme',dark?'dark':'light')}catch{}}
theme(preference?preference==='dark':matchMedia('(prefers-color-scheme: dark)').matches);$('theme').onclick=()=>theme(!document.body.classList.contains('dark'));
function duration(){const seconds=started?Math.floor(((ended||Date.now())-started)/1000):0;return [Math.floor(seconds/60),seconds%60].map(v=>String(v).padStart(2,'0')).join(':')}
setInterval(()=>$('clock').textContent=duration(),1000);
function message(text){$('error').textContent=text;$('error').focus()}
function go(next){step=next;render();$('stageTitle').focus();$('stage').scrollIntoView({block:'start',behavior:'auto'})}
function buttons(back,next,label){return `<div id="error" class="error" role="alert" tabindex="-1"></div><div class="actions"><span class="small">${started?'Registro simulado en curso':'No se realizará una llamada real'}</span><div class="right">${back?'<button type="button" id="back">← Volver</button>':''}<button type="button" class="primary" id="next">${label} →</button></div></div>`}
function render(){document.querySelectorAll('.journey div').forEach((el,i)=>{el.className=i===Math.min(step,3)?'current':i<step?'done':'';if(i===Math.min(step,3))el.setAttribute('aria-current','step');else el.removeAttribute('aria-current')});$('callstatus').textContent=closed?'✓ Simulación cerrada':started?'● Registro simulado en curso':'○ Listo para comenzar';$('notes').disabled=closed;
 if(step===0){$('stage').innerHTML=`<div class="kicker">Antes de llamar</div><h2 id="stageTitle" tabindex="-1">Una persona.<br>Una conversación.</h2><p class="lead">Confirma con quién vas a hablar. El registro comienza cuando estés listo para marcar en MicroSIP.</p><fieldset><legend>Persona de contacto</legend><label class="choice"><input type="radio" checked name="person"><span><strong>Mariana López</strong><small>Compras · Contacto de ejemplo</small></span></label></fieldset><h3>Teléfono seleccionado</h3><div class="phone">662 000 0000 <small style="font-size:13px">ext. 104</small></div><p class="small">Número ficticio. Esta demostración no marca ni se conecta a MicroSIP.</p><label class="check"><input id="withSurvey" type="checkbox" ${withSurvey?'checked':''}><span>Incluir una encuesta de ejemplo.<br><small>Desactívala para probar un escenario sin encuesta, como no contesta o buzón.</small></span></label>${buttons(false,true,'Iniciar simulación')}`;$('withSurvey').onchange=e=>withSurvey=e.target.checked;$('next').onclick=()=>{started=Date.now();go(withSurvey?1:2)}}
 if(step===1){$('stage').innerHTML=`<div class="kicker">Guía de conversación · SILIMEX</div><h2 id="stageTitle" tabindex="-1">Escucha primero.<br>Registra lo importante.</h2><p class="guide">“Hola, Mariana. Mi nombre es Ana, de Vincco. ¿Tienes un momento para conversar sobre los productos que utilizan en su negocio?”</p><div class="progress">PREGUNTA ${question+1} / ${questions.length} · ENCUESTA ILUSTRATIVA</div><fieldset ${declined?'disabled':''}><legend>${questions[question]}</legend><div class="selection">${options[question].map(v=>`<label class="choice"><input type="radio" name="answer" value="${esc(v)}" ${answers[question]===v?'checked':''}><span>${v}</span></label>`).join('')}</div></fieldset><label class="check"><input id="declined" type="checkbox" ${declined?'checked':''}><span>El contacto no desea contestar la encuesta.</span></label><p class="small">Si no hay respuesta, no registres un rechazo como si lo hubiera expresado el contacto.</p>${buttons(question>0,true,declined||question===1?'Elegir canalización':'Siguiente pregunta')}`;document.querySelectorAll('[name=answer]').forEach(el=>el.onchange=()=>answers[question]=el.value);$('declined').onchange=e=>{declined=e.target.checked;render()};if($('back'))$('back').onclick=()=>{question--;render()};$('next').onclick=()=>{if(!declined&&!answers[question])return message('Selecciona una respuesta para continuar.');if(!declined&&question===0){question++;render();$('stageTitle').focus()}else go(2)}}
 if(step===2){$('stage').innerHTML=`<div class="kicker">Resultado de la llamada</div><h2 id="stageTitle" tabindex="-1">Elige la canalización.<br>Conoce su consecuencia.</h2><p class="lead">La canalización describe lo que ocurrió. Su disposición ya está definida por administración; el agente no la cambia.</p><fieldset><legend>Catálogo inicial del proyecto · Opciones clasificadas</legend><div class="channel-list">${channels.map(([code,label,disposition])=>`<label class="channel"><input type="radio" name="channel" value="${code}" ${channel===code?'checked':''}><span><strong>${label}</strong><small>${disposition==='BLACKLIST'?'Blacklist':disposition==='EXITOSO'?'Exitoso':disposition==='SEGUIMIENTO'?'Seguimiento':'No contesta'}</small></span></label>`).join('')}</div></fieldset><div id="consequence"></div><details><summary>¿Por qué faltan otras canalizaciones?</summary><p>En el catálogo inicial, AGENDA_LLAMADA, NUEVOS_DATOS, SOLICITA_COTIZACION, QUEJA y otras opciones están pendientes de clasificación. Solo estarán disponibles cuando administración les asigne una disposición. Este borrador no consulta el catálogo de tu base de datos actual.</p></details>${buttons(withSurvey,true,'Revisar cierre')}`;document.querySelectorAll('[name=channel]').forEach(el=>el.onchange=()=>{channel=el.value;consequence()});consequence();if($('back'))$('back').onclick=()=>go(1);$('next').onclick=()=>{if(!channel)return message('Selecciona una canalización antes de continuar.');if(withSurvey&&['NO_CONTESTA','BUZON'].includes(channel))return message('Esta simulación incluye una encuesta de conversación. Para probar no contesta o buzón, inicia otra simulación sin encuesta. No registraremos un rechazo que el contacto no expresó.');if(channel==='NUEVOS_DATOS_RAZON_SOCIAL'&&(!newBusiness.trim()||newBusiness.trim()==='Soluciones del Noroeste'))return message('Escribe una razón social diferente para simular su actualización.');go(3)}}
 if(step===3){const chosen=channels.find(c=>c[0]===channel);$('stage').innerHTML=`<div class="kicker">Última revisión</div><h2 id="stageTitle" tabindex="-1">Así quedará<br>esta conversación.</h2><p class="lead">Revisa el resultado antes de cerrar el registro simulado.</p><dl class="summary"><div><dt>Contacto</dt><dd>Mariana López</dd></div><div><dt>Campaña</dt><dd>SILIMEX</dd></div><div><dt>Canalización</dt><dd>${chosen[1]}</dd></div><div><dt>Disposición</dt><dd>${chosen[2]}</dd></div><div class="wide"><dt>Encuesta</dt><dd>${!withSurvey?'Escenario sin encuesta':declined?'El contacto no desea contestar':answers.map(esc).join(' · ')}</dd></div>${channel==='NUEVOS_DATOS_RAZON_SOCIAL'?'<div class="wide"><dt>Nueva razón social</dt><dd>'+esc(newBusiness)+'</dd></div>':''}<div class="wide"><dt>Notas</dt><dd>${esc($('notes').value)||'Sin notas'}</dd></div></dl>${chosen[2]==='BLACKLIST'?'<div class="warning">En el sistema real, esta canalización envía el contacto a Blacklist.</div><label class="check"><input id="ack" type="checkbox"><span>Entiendo la consecuencia de esta canalización.</span></label>':'<div class="info">Seleccionar esta canalización registra el resultado. No envía un correo desde este borrador.</div>'}${buttons(true,true,'Cerrar simulación')}`;$('back').onclick=()=>go(2);$('next').onclick=()=>{if($('ack')&&!$('ack').checked)return message('Confirma que has revisado la consecuencia de Blacklist.');ended=Date.now();closed=true;go(4)}}
 if(step===4){const chosen=channels.find(c=>c[0]===channel);$('stage').innerHTML=`<div class="success-mark" aria-hidden="true">✓</div><div class="kicker">Recorrido completado</div><h2 id="stageTitle" tabindex="-1">Conversación cerrada.<br>Resultado claro.</h2><p class="lead">Has completado la simulación de una llamada. No se guardó información en el sistema ni se enviaron correos.</p><dl class="summary"><div><dt>Duración de la simulación</dt><dd>${duration()}</dd></div><div><dt>Disposición</dt><dd>${chosen[2]}</dd></div><div class="wide"><dt>Canalización</dt><dd>${chosen[1]}</dd></div></dl><div class="actions"><span class="small">Datos de ejemplo · Sin efectos reales</span><button class="primary" id="restart">Simular otra llamada →</button></div>`;$('restart').onclick=()=>{step=0;question=0;answers=['',''];declined=false;channel='';started=0;ended=0;closed=false;withSurvey=true;newBusiness='';$('notes').value='';$('clock').textContent='00:00';go(0)}}
}
function consequence(){const c=channels.find(c=>c[0]===channel);$('consequence').innerHTML=c?`<div class="${c[2]==='BLACKLIST'?'warning':'info'}">${c[2]==='BLACKLIST'?'Esta canalización envía el contacto a Blacklist en el sistema real.':c[2]==='EXITOSO'?'Se registrará como Exitoso. Elegirla no envía automáticamente una promoción.':'Se conservará la disposición asignada por administración.'}</div>`:'';if(c&&channel==='NUEVOS_DATOS_RAZON_SOCIAL'){$('consequence').innerHTML+='<label class="new-business" for="newBusiness">Nueva razón social<input id="newBusiness" type="text" value="'+esc(newBusiness)+'" autocomplete="off"></label>';$('newBusiness').oninput=e=>newBusiness=e.target.value}}
render();
